In [1]:
import numpy as np
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

sns.set_style('whitegrid')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [2]:
tags = pd.read_csv('/Users/katerinacapouskova/Desktop/DSI-SF-4-katerinaC/Projects/Capstone/Movies/ml-latest/tags.csv')

In [3]:
df = pd.read_csv('/Users/katerinacapouskova/Desktop/DSI-SF-4-katerinaC/Projects/Capstone/Movies/ml-latest/movies_ratings_user_stripped.csv')

In [4]:
movies = pd.read_csv('/Users/katerinacapouskova/Desktop/DSI-SF-4-katerinaC/Projects/Capstone/Movies/ml-latest/movies_new.csv')

In [5]:
df = df.sort('userId').reset_index()

/Applications/anaconda/envs/dsi/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [6]:
df.head()

,index,Unnamed: 0,userId,movieId,rating_x,ratings_mean,title,genres,user_avg_rating,rating_mean_stand
0,0,0,1,122,2.0,2.862931,Boomerang (1992),Comedy|Romance,2.666667,-0.666667
1,52646,52646,1,1441,4.0,3.544102,Benny & Joon (1993),Comedy|Romance,2.666667,1.333333
2,59369,59369,1,1961,3.0,3.911195,Rain Man (1988),Drama,2.666667,0.333333
3,89159,89159,1,1972,1.0,2.214472,"Nightmare on Elm Street 5: The Dream Child, A ...",Horror,2.666667,-1.666667
4,18138,18138,1,1221,5.0,4.263098,"Godfather: Part II, The (1974)",Crime|Drama,2.666667,2.333333

In [7]:
movies_df = movies.drop(['Unnamed: 0', 'ratings_count', 'COMEDY', 'DRAMA', 'CRIME', 'FANTASY', 'FILM-NOIR', 
        'MUSICAL', 'SCI-FI', 'MYSTERY', 'WAR', 'Year', 'title_list',
                         'THRILLER', 'WESTERN', 'ROMANCE', 'ADVENTURE', 'ANIMATION',
        'CHILDRENS', 'DOCUMENTARY', 'HORROR'], axis=1)

In [8]:
df = df.drop(['Unnamed: 0','index'], axis=1)

### Modify the genres column:

In [9]:
def replace(x):
    
    y = str(x)
    y = y.replace("|",(", "))
    
    return y
            

#df['genres_list'] = df['genres'].map(replace)
movies_df['genres_list'] = movies_df['genres'].map(replace)

In [10]:
movies_df.head()

,movieId,ratings_mean,title,genres,genres_list
0,1,3.889300,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy"
1,2,3.229527,Jumanji (1995),Adventure|Children|Fantasy,"Adventure, Children, Fantasy"
2,3,3.178142,Grumpier Old Men (1995),Comedy|Romance,"Comedy, Romance"
3,4,2.879433,Waiting to Exhale (1995),Comedy|Drama|Romance,"Comedy, Drama, Romance"
4,5,3.080410,Father of the Bride Part II (1995),Comedy,Comedy

In [11]:
movies_df.shape

(32573, 5)

### Merge with tags:

In [12]:
df_movies = movies_df.merge(tags, how='right', left_on='movieId', right_on='movieId')

In [13]:
df_movies['tag'] = df_movies['tag'].map(lambda x: str(x))

In [14]:
def comma(x):
    x = x+','
    
    return x

df_movies['tag'] = df_movies['tag'].map(comma)

In [15]:
def comma(x):
    x = str(x)
    x = x+','
    
    
    return x

df_movies['genres_list'] = df_movies['genres_list'].map(comma)

In [16]:
def comma_2(x):
    x = x.replace(' ',',')
    return x
df_movies['tag'] = df_movies['tag'].map(comma_2)

In [17]:
df_movies['tag'] = df_movies['tag'].map(lambda x: str(x))

In [18]:
df_movies.head(40)

,movieId,ratings_mean,title,genres,genres_list,userId,tag,timestamp
0,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",323,"want,to,see,again,",1147206650
1,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",687,"animation,",1400002011
2,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",687,"comedy,",1400002031
3,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",687,"Disney,",1400002025
4,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",687,"Pixar,",1400002008
5,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",2315,"computer,animation,",1206662843
6,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",2315,"Pixar,",1206662843
7,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"animated,",1312088976
8,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"animation,",1312088979
9,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"children,",1312088964
10,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"comedy,",1312088984
11,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"fantasy,",1312088987
12,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"funny,",1312088970
13,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"humorous,",1312088973
14,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"Pixar,",1312088967
15,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",3893,"time,travel,",1312088989
16,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",5167,"avi,",1137440588
17,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",5167,"buy,",1137440588
18,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6291,"family,",1461947270
19,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6291,"friendship,",1461947273
20,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6291,"pixar,",1461947267
21,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6827,"Animation,",1464050712
22,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6827,"Cartoon,",1464049775
23,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",6827,"Pixar,",1464049772
24,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",7865,"animation,",1253632651
25,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",7865,"Pixar,",1253632645
26,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",8509,"animation,",1165074625
27,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",8509,"erlend's,DVDs,",1165074618
28,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",11202,"pixar,",1445443245
29,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",13862,"animation,",1430887659
30,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",13862,"comedy,",1430887659
31,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",13862,"kids,",1430887659
32,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",18912,"computer,animation,",1451035426
33,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",18912,"pixar,",1451035426
34,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"animated,",1285014825
35,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"animation,",1285014815
36,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"buddy,movie,",1285014833
37,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"children,",1285014830
38,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"clever,",1285014854
39,1.0,3.8893,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,"Adventure, Animation, Children, Comedy, Fantasy,",24116,"time,travel,",1285014839

In [19]:
movies_tags = df_movies.groupby(['movieId','ratings_mean', 'title', 'genres_list'])['tag'].sum()

In [20]:
movies_tags = pd.DataFrame(movies_tags).reset_index()

In [21]:
movies_tags.head()

,movieId,ratings_mean,title,genres_list,tag
0,1.0,3.889300,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy,","want,to,see,again,animation,comedy,Disney,Pixa..."
1,2.0,3.229527,Jumanji (1995),"Adventure, Children, Fantasy,","adapted,from:book,childish,Children,kid,flick,..."
2,3.0,3.178142,Grumpier Old Men (1995),"Comedy, Romance,","sequel,fever,funny,Funniest,Movies,sequel,CLV,..."
3,4.0,2.879433,Waiting to Exhale (1995),"Comedy, Drama, Romance,","chick,flick,revenge,characters,CLV,girl,movie,..."
4,5.0,3.080410,Father of the Bride Part II (1995),"Comedy,","sequel,fever,childhood,classics,steve,martin,D..."

### Make a new column with genres, tags and rating:

In [22]:
movies_tags['sent'] = movies_tags[['genres_list','tag', 'ratings_mean']].apply(lambda x: '{}  {}  {}'.format(x[0],x[1],x[2]), axis=1)    
movies_tags['sentence'] = movies_tags['sent'].map(lambda x: str(x))
del movies_tags['sent']

In [23]:
movies_tags.head()

,movieId,ratings_mean,title,genres_list,tag,sentence
0,1.0,3.889300,Toy Story (1995),"Adventure, Animation, Children, Comedy, Fantasy,","want,to,see,again,animation,comedy,Disney,Pixa...","Adventure, Animation, Children, Comedy, Fantas..."
1,2.0,3.229527,Jumanji (1995),"Adventure, Children, Fantasy,","adapted,from:book,childish,Children,kid,flick,...","Adventure, Children, Fantasy, adapted,from:bo..."
2,3.0,3.178142,Grumpier Old Men (1995),"Comedy, Romance,","sequel,fever,funny,Funniest,Movies,sequel,CLV,...","Comedy, Romance, sequel,fever,funny,Funniest,..."
3,4.0,2.879433,Waiting to Exhale (1995),"Comedy, Drama, Romance,","chick,flick,revenge,characters,CLV,girl,movie,...","Comedy, Drama, Romance, chick,flick,revenge,c..."
4,5.0,3.080410,Father of the Bride Part II (1995),"Comedy,","sequel,fever,childhood,classics,steve,martin,D...","Comedy, sequel,fever,childhood,classics,steve..."

In [36]:
movies_tags.sentence[122]

'Comedy, War,  politics,politics,politics,politics,politics,politics,politics,politics,politics,politics,politics,Michael,Moore,sarcasm,politics,politics,Michael,Moore,politics,politics,conspiracy,politics,John,Candy,politics,Alan,Alda,Dan,Aykroyd,funny,hilarious,irreverent,James,Belushi,John,Candy,Michael,Moore,military,political,commentary,politics,Rhea,Perlman,Rip,Torn,sarcasm,satire,war,politics,politics,  2.7922483468'

In [25]:
movies_tags.shape

(18228, 6)

## Recommendation function:

In [107]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel

def recommendation(user, df):
    
    #define y (we look for similar movies to y)
    
    y = user.title.iloc[0]
    y = df[df.title == y].index.tolist()
    for i in y:
        y = int(i)
    
    
    
    #take only movies_tags.sentence for analysis
    
    movies_sentence = df['sentence']
    
    # set up tfidf vectorizer to map movies' tag in a dimensional space to assign a numerical value
    tf_vectorizer = TfidfVectorizer(ngram_range=(1, 2))
    tfidf_matrix = tf_vectorizer.fit_transform(movies_sentence)
    #tfidf_y = tf_vectorizer.fit_transform(y)
     
    # set up a cosine similarity     
    cosine_similarities = cosine_similarity(tfidf_matrix[y:y+1], tfidf_matrix).flatten()
    
    related_movies_indices = cosine_similarities.argsort()[:-7:-1]
    
    #Probability of liking:
    user_rating = user.rating_x.iloc[0]
    max_rating = 5
    similarity = cosine_similarities[related_movies_indices]
    user_average = user.user_avg_rating.iloc[0]
    
    probability = (user_rating/max_rating)*similarity
    
    similarity_df = pd.DataFrame({
            'Movies_indices': related_movies_indices,
            'Cosine_similarity': cosine_similarities[related_movies_indices],
            'Probability of liking': probability
        })
    similarity = similarity_df.merge(df, how='left', left_on='Movies_indices', right_index=True)
    
    print similarity

In [27]:
user = df[(df['userId'] == 45) & (df['movieId'] == 122)]

In [28]:
user = pd.DataFrame(user)

In [29]:
user.head()

,userId,movieId,rating_x,ratings_mean,title,genres,user_avg_rating,rating_mean_stand
3508,45,122,1.0,2.862931,Boomerang (1992),Comedy|Romance,2.44863,-1.44863

In [108]:
recommendation(user, movies_tags)

   Cosine_similarity  Movies_indices  Probability of liking   movieId  \
0           1.000000              97               0.200000     122.0
1           0.364467           10509               0.072893   73991.0
2           0.322353            4087               0.064471    5278.0
3           0.291772            7271               0.058354   31750.0
4           0.266315            8591               0.053263   52227.0
5           0.265734           16152               0.053147  129080.0

   ratings_mean                       title                  genres_list  \
0      2.862931            Boomerang (1992)             Comedy, Romance,
1      1.500000              Pyrates (1991)             Comedy, Romance,
2      2.100000  Fraternity Vacation (1985)             Comedy, Romance,
3      2.600000      Until September (1984)              Drama, Romance,
4      3.031447   Darwin Awards, The (2006)  Adventure, Comedy, Romance,
5      1.750000      La montaña rusa (2012)             Comedy, Romance,

                                                 tag  \
0  Nudity,(Topless,-,Brief),Can't,remember,CLV,da...
1                                  nudity,(topless),
2                              nudity,(topless),CLV,
3                                  nudity,(topless),
4  Nudity,(Topless,-,Brief),dark,comedy,Nudity,(T...
5                                  nudity,(topless),

                                            sentence
0  Comedy, Romance,  Nudity,(Topless,-,Brief),Can...
1           Comedy, Romance,  nudity,(topless),  1.5
2       Comedy, Romance,  nudity,(topless),CLV,  2.1
3            Drama, Romance,  nudity,(topless),  2.6
4  Adventure, Comedy, Romance,  Nudity,(Topless,-...
5          Comedy, Romance,  nudity,(topless),  1.75